language: node_js
node_js:
- '8'
dist: trusty
before_install: |
  set -e
  date
install: |
  set -e
  date
script: ./.travis/test.sh
after_failure: tail -n +1 -- /home/travis/.npm/_logs/*-debug.log
cache:
  directories:
  - node_modules
services:
